version: 2

models:
  - name: stg_transactions
    description: "Cleaned and standardized transaction data"
    columns:
      - name: transaction_id
        description: "Primary key"
        data_tests:
          - unique
          - not_null
      - name: account_id
        description: "Account identifier"
        data_tests:
          - not_null
      - name: amount
        description: "Absolute transaction amount"
        data_tests:
          - not_null
      - name: signed_amount
        description: "Signed amount (negative for debits)"
        data_tests:
          - not_null
      - name: transaction_type
        description: "credit or debit"
        data_tests:
          - accepted_values:
              values: ['credit', 'debit']
      - name: category
        description: "Transaction category"
        data_tests:
          - not_null
      - name: transaction_date
        description: "Date of transaction"
        data_tests:
          - not_null

  - name: stg_exchange_rates
    description: "Cleaned exchange rate data"
    columns:
      - name: rate_date
        description: "Date of the exchange rate"
        data_tests:
          - not_null
      - name: base_currency
        description: "Base currency (GBP)"
        data_tests:
          - not_null
      - name: target_currency
        description: "Target currency (USD, EUR)"
        data_tests:
          - not_null
      - name: rate
        description: "Exchange rate value"
        data_tests:
          - not_null
