version: 2

sources:
  - name: raw
    description: "Raw data ingested from various sources"
    schema: raw
    
    tables:
      - name: transactions
        description: "Raw transaction data from bank feeds"
        columns:
          - name: transaction_id
            description: "Unique transaction identifier"
            data_tests:
              - unique
              - not_null
          - name: account_id
            description: "Account identifier"
            data_tests:
              - not_null
          - name: amount
            description: "Transaction amount (always positive)"
            data_tests:
              - not_null
          - name: transaction_type
            description: "credit or debit"
            data_tests:
              - accepted_values:
                  values: ['credit', 'debit']
          - name: transaction_date
            description: "Date of transaction"
            data_tests:
              - not_null

      - name: exchange_rates
        description: "Daily exchange rates from Frankfurter API"
        columns:
          - name: rate_date
            description: "Rate date"
            data_tests:
              - not_null
          - name: base_currency
            description: "Base currency code"
            data_tests:
              - not_null
          - name: target_currency
            description: "Target currency code"
            data_tests:
              - not_null
          - name: rate
            description: "Exchange rate"
            data_tests:
              - not_null
