name: 'budgetbox'
version: '1.0.0'
config-version: 2

profile: 'budgetbox'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets:
  - "target"
  - "dbt_packages"

# Model configurations
models:
  budgetbox:
    # Staging models - views for fast iteration
    staging:
      +materialized: view
      +schema: staging
      +tags: ["staging"]

    # Mart models - tables for analytics
    marts:
      +materialized: table
      +schema: marts
      +tags: ["marts"]

# Variable defaults
vars:
  # Default currency (all transactions are GBP in first slice)
  base_currency: 'GBP'
