version: 2

models:
  - name: dim_dates
    description: "Date dimension for time-based analytics"
    columns:
      - name: date_key
        description: "Primary key (YYYYMMDD)"
        data_tests:
          - unique
          - not_null
      - name: full_date
        description: "Full date value"
        data_tests:
          - unique
          - not_null

  - name: dim_accounts
    description: "Account dimension"
    columns:
      - name: account_key
        description: "Surrogate key"
        data_tests:
          - unique
          - not_null
      - name: account_id
        description: "Natural key"
        data_tests:
          - unique
          - not_null
      - name: account_type
        description: "Account type"
        data_tests:
          - not_null
          - accepted_values:
              values: ['current', 'savings', 'credit']
      - name: currency
        description: "Account currency"
        data_tests:
          - not_null

  - name: dim_categories
    description: "Transaction category dimension with hierarchy"
    columns:
      - name: category_key
        description: "Surrogate key"
        data_tests:
          - unique
          - not_null
      - name: category_id
        description: "Natural key"
        data_tests:
          - unique
          - not_null
      - name: category_type
        description: "income or expense"
        data_tests:
          - not_null
          - accepted_values:
              values: ['income', 'expense']
      - name: parent_category
        description: "Parent category grouping"
        data_tests:
          - not_null
      - name: budget_category
        description: "Budget classification"
        data_tests:
          - not_null
          - accepted_values:
              values: ['Essential', 'Semi-Essential', 'Discretionary']

  - name: fact_transactions
    description: "Central fact table with GBP-converted amounts"
    columns:
      - name: transaction_key
        description: "Surrogate key"
        data_tests:
          - unique
          - not_null
      - name: transaction_id
        description: "Natural key"
        data_tests:
          - unique
          - not_null
      - name: date_key
        description: "FK to dim_dates"
        data_tests:
          - not_null
          - relationships:
              to: ref('dim_dates')
              field: date_key
      - name: account_key
        description: "FK to dim_accounts"
        data_tests:
          - not_null
          - relationships:
              to: ref('dim_accounts')
              field: account_key
      - name: category_key
        description: "FK to dim_categories"
        data_tests:
          - not_null
          - relationships:
              to: ref('dim_categories')
              field: category_key
      - name: amount
        description: "Amount in original currency"
        data_tests:
          - not_null
      - name: signed_amount
        description: "Signed amount in original currency"
        data_tests:
          - not_null
      - name: amount_gbp
        description: "Amount converted to GBP"
        data_tests:
          - not_null
      - name: signed_amount_gbp
        description: "Signed amount in GBP"
        data_tests:
          - not_null
      - name: transaction_type
        description: "credit or debit"
        data_tests:
          - not_null
          - accepted_values:
              values: ['credit', 'debit']
      - name: was_converted
        description: "Whether currency conversion was applied"
        data_tests:
          - not_null
